<?php
require "../vistas/inicio.html";
require "../vistas/vistaDetalle.php"; //Primera parte de la página principal, contiene el header

?>

<div id='legal'> <!-- Todo esto es como el lore ipsum -->
    <a href="../controladores/validar.php">Volver</a><br><br>
    <h1>Aviso de Privacidad de Amasón.es</h1><br>
    <p>
        <strong>Responsables de la información personal</strong><br><br>
        Amasón Europe Core SARL, Amasón EU SARL, Amasón Services Europe SARL y Amasón Media EU SARL, las cuatro con dirección en el número 38 Avenue John F. Kennedy, L-1855, Luxemburgo, y Amasón Digital UK Limited, con dirección en el número 1 de Principal Place, Worship Street, Londres, EC2A 2FA, Reino Unido (de forma conjunta, "Amasón Europa") son responsables del tratamiento de la información personal recabada y tratada a través de los Servicios de Amasón. Se puede obtener más información aquí.
        
        <br><br><strong>¿Qué información personal de clientes recaba Amasón Europa?</strong><br><br>
        Recabamos tu información personal para prestar y mejorar de forma continua nuestros productos y servicios.
        
        Estos son los tipos de información personal que recabamos:
        
        Información que nos facilitas: recibimos y almacenamos toda la información que nos facilitas en relación con los Servicios de Amasón. Haz clic aquí para ver algunos ejemplos de información que recopilamos. Puedes elegir no facilitar cierta información, pero si así lo haces, no podrás disfrutar de muchos de los Servicios de Amasón.
        Información automática: recopilamos y almacenamos de forma automática ciertos tipos de información sobre el uso que haces de los Servicios de Amasón, incluyendo tu interacción con el contenido y los servicios disponibles a través de los Servicios de Amasón. Por ejemplo, al igual que hacen muchas otras páginas web, utilizamos "cookies" y otros identificadores únicos para recabar cierta información cuando tu navegador de Internet o tu dispositivo acceden a los Servicios de Amasón y a otros tipos de contenidos que te son ofrecidos por parte de o en nombre de Amasón Europa en otras páginas web. Haz clic aquí para ver ejemplos de lo que recabamos.
        Información procedente de otras fuentes: es posible que recibamos información sobre ti de otras fuentes, como, por ejemplo, información actualizada sobre tu dirección y sobre entregas procedente de nuestros transportistas, que utilizamos para actualizar nuestros registros y realizar la próxima entrega con mayor facilidad. Haz clic aquí para ver algunos ejemplos de la información que recibimos.
        ¿Con qué finalidades trata tu información personal Amasón Europa?
        Tratamos tu información personal para operar, prestar y mejorar los Servicios de Amasón que ofrecemos a nuestros clientes. Entre estas finalidades se incluyen:
        
        Compra y entrega de productos y servicios. Utilizamos tu información personal para aceptar y gestionar pedidos, entregar productos y servicios, procesar pagos y comunicarnos contigo en relación con pedidos, productos, servicios y ofertas promocionales.
        Prestación, resolución de problemas y mejora de los Servicios de Amasón. Utilizamos tu información personal para aportar funcionalidad, analizar el rendimiento, resolver errores y mejorar la usabilidad y efectividad de los Servicios de Amasón.
        Recomendaciones y personalización. Utilizamos tu información personal para recomendar funcionalidades, productos y servicios que puedan interesarte, identificar tus preferencias y personalizar tu experiencia con los Servicios de Amasón.
        Prestación de servicios de voz, imagen y cámara. Cuando utilizas los servicios de voz, imagen y cámara tratamos la entrada de voz, imágenes, vídeos y otra información personal para dar respuesta a tus peticiones, prestarte el servicio solicitado y mejorar nuestros servicios de Amasón. Si deseas obtener más información sobre los servicios de voz de Alexa, haz clic aquí.
        Cumplimiento de obligaciones legales. En algunos casos, recopilamos y utilizamos tu información personal para cumplir con la ley. Por ejemplo, recabamos información de terceros vendedores sobre el lugar de establecimiento y la cuenta bancaria para verificación de identidad, entre otras finalidades.
        Comunicarnos contigo. Utilizamos tu información personal para comunicarnos contigo en relación con los Servicios de Amasón a través de diferentes canales (por ejemplo, por teléfono, correo electrónico, chat).
        Publicidad. Utilizamos información como tus interacciones con sitios, contenido o servicios de Amasón para mostrar anuncios basados en funcionalidades, productos y servicios que puedan interesarte. No utilizamos tu información personal para mostrarte anuncios basados en tus intereses. Para más información, puedes consultar nuestro Aviso sobre publicidad basada en los intereses del usuario.
        Prevención del fraude y riesgos crediticios. Tratamos información personal para prevenir y detectar el fraude y el abuso con el fin de proteger la seguridad de nuestros clientes, Amasón Europa y otros. También podemos utilizar métodos de calificación para evaluar y gestionar los riesgos crediticios.
        Finalidades para las que recabamos tu consentimiento. También podemos solicitar tu consentimiento para tratar tu información personal con una finalidad concreta que te comunicaremos. Cuando prestes tu consentimiento para que tratemos tu información personal para una finalidad determinada, podrás revocarlo en cualquier momento y dejaremos de tratar tu información con esa finalidad.
        Información sobre cookies y otros identificadores
        Utilizamos cookies y herramientas similares para mejorar tu experiencia de compra, prestar nuestros servicios y entender cómo utilizan los clientes nuestros servicios con el fin de realizar mejoras y mostrar publicidad. Terceras partes aprobadas también utilizan estas herramientas en relación con la publicidad mostrada. Para obtener más información acerca de las cookies y de cómo las utilizamos, por favor lee nuestro Aviso de Cookies. Puedes gestionar tus preferencias sobre cookies aquí.
        
        <br><br><strong>¿Comparte Amasón Europa tu información personal?</strong><br><br>
        La información relativa a nuestros clientes es una parte fundamental de nuestro negocio y no participamos en actividades de venta de la información personal de nuestros clientes a terceros. Amasón Europa sólo comparte la información personal de sus clientes del modo descrito a continuación, con Amasón.com, Inc. y con filiales bajo el control de Amasón.com, Inc. que o bien estén sujetas al presente Aviso de Privacidad o sigan prácticas al menos tan protectoras como las descritas en este Aviso de Privacidad.
        
        Operaciones con terceros. Ponemos a tu disposición servicios, productos, aplicaciones o Skills proporcionadas por terceros para su uso a través de los Servicios de Amasón. Por ejemplo, puedes encargar productos de terceros vendedores a través de nuestras tiendas, descargar aplicaciones de terceros proveedores a través de nuestra App Store y habilitar Skills de terceros mediante los servicios de Alexa. También ofrecemos servicios o vendemos líneas de producto conjuntamente con terceras empresas, como tarjetas bajo marca compartida. Conocerás cuando haya terceros involucrados en tus operaciones y compartamos tu información personal relacionada con esas operaciones con dichos terceros.
        Terceros proveedores de servicios. Contratamos a otras sociedades y personas para realizar ciertas funciones por nuestra cuenta. Algunas de las funciones que realizan pueden ser: ejecutar pedidos de productos y servicios, enviar paquetes, enviar correos postales y electrónicos, eliminar información repetida de las listas de clientes, realizar análisis de datos, ofrecer asistencia de marketing, ofrecer resultados de búsquedas y enlaces (incluidos enlaces y listados de pago), procesar pagos, transmitir contenidos, valorar y gestionar riesgos crediticios y ofrecer servicio de atención al cliente. Estos terceros proveedores de servicios tendrán acceso a la información personal necesaria para realizar sus funciones, pero no podrán utilizarla para otros fines. Además, deberán tratar la información personal de conformidad con el presente Aviso de Privacidad y la legislación aplicable en materia de protección de datos.
        Transmisiones de sociedades. A medida que desarrollamos nuestro negocio, podemos comprar o vender otras sociedades o servicios. En dichas transacciones, uno de los activos de las sociedades transferidas suele ser la información personal de los clientes; dicha información estará en todo caso sujeta a los compromisos adquiridos en los Avisos de Privacidad preexistentes (a menos, claro está, que el cliente lo autorice de otro modo). Por supuesto, en el improbable caso de que Amasón.com, Inc. o la mayor parte de sus activos sean adquiridos por un tercero, la información personal de los clientes sería uno de los activos transferidos.
        Protección de Amasón Europa y otros. Divulgamos información personal y datos de cuentas de nuestros clientes cuando creemos que su divulgación es necesaria para el cumplimiento de la ley, para hacer cumplir o aplicar las Condiciones de Uso y Venta y otros acuerdos o para proteger los derechos, la propiedad, o seguridad de Amasón Europa, sus usuarios, o terceros. Lo anterior incluye el intercambio de información con otras sociedades y organizaciones para la protección contra el fraude y la reducción del riesgo de crédito.
        Aparte de lo establecido anteriormente, se te informará en el caso de que cualquier información sobre ti se comparta con terceras partes, al objeto de que tengas la oportunidad de elegir que no se comparta tu información.
        
        Transferencias fuera del Espacio Económico Europeo. Siempre que transmitamos información personal a países situados fuera del Espacio Económico Europeo, nos aseguraremos de que la información es transferida de acuerdo con este Aviso de Privacidad y conforme a lo permitido por las leyes aplicables en materia de protección de datos. Nos basamos en las decisiones de la Comisión Europea sobre adecuación o utilizamos contratos con garantías estándar publicados por la Comisión Europea (puedes solicitar una copia al Servicio de Atención al Cliente.
        
        <br><br><strong>¿Está a salvo mi información personal?</strong><br><br>
        Diseñamos nuestros sistemas y dispositivos teniendo en cuenta tu seguridad y privacidad.
        
        Trabajamos para proteger la seguridad de tu información personal durante la transmisión utilizando software y protocolos de encriptación.
        Al gestionar datos de tarjetas de crédito, cumplimos los Estándares de Seguridad de los Datos de la Industria de las Tarjetas de Pago (PCI DSS).
        Contamos con sistemas de seguridad físicos, electrónicos y procedimentales en relación con la recogida, almacenamiento, y divulgación de información personal del cliente. Nuestros procedimientos de seguridad implican que podemos pedirte que verifiques tu identidad antes de facilitarte información confidencial.
        Nuestros dispositivos ofrecen funcionalidades de seguridad que los protegen frente a accesos no autorizados y pérdidas de datos. Puedes controlar esas funcionalidades y configurarlas en función de tus necesidades. Haz clic aquí para más información sobre cómo gestionar la configuración de seguridad de tu dispositivo.
        Es importante que te protejas contra el acceso no autorizado de terceros a tu contraseña y a tus ordenadores, dispositivos y aplicaciones. Te recomendamos que utilices una contraseña única para tu cuenta de Amasón que no utilices para otras cuentas online. Comprueba que cierras tu sesión al acabar siempre que estés utilizando un ordenador compartido. Haz clic aquí para obtener más información sobre cómo cerrar tu sesión.
        Publicidad
        Terceras partes anunciantes y enlaces a otras webs: los Servicios de Amasón pueden incluir publicidad de terceros y accesos a otras páginas web y aplicaciones. Las terceras partes anunciantes podrán recabar información tuya cuando interactúes con sus contenidos, anuncios, y servicios. Para obtener más información acerca de publicidad de terceros en Amasón Europa, incluyendo anuncios basados en tus intereses, consulta nuestro Aviso sobre publicidad basada en los intereses del usuario. Para realizar ajustes en tus preferencias de publicidad, consulta la página de Preferencias de Publicidad.
        Uso de servicios de publicidad de terceros: proporcionamos a empresas de publicidad información que les permite presentarte anuncios de Amasón más útiles y relevantes y medir su efectividad. Nunca compartimos tu nombre ni otra información que te identifique directamente, sino que utilizamos un identificador publicitario como una cookie, otro tipo de identificador, o un código derivado de la aplicación de criptografía irreversible a otra información, como una dirección de correo electrónico. Por ejemplo: si ya has descargado una de nuestras apps, compartiremos tu identificador publicitario y datos sobre la descarga para que no se te vuelva a presentar un anuncio de descarga de la app. Algunas empresas de publicidad también utilizan esta información para presentarte anuncios relevantes de otros anunciantes. Puedes conseguir más información sobre cómo desistir de la publicidad basada en intereses en la página de Preferencias de Publicidad.
        ¿A qué información tengo acceso?
        Puedes acceder a tus datos, incluyendo tu nombre, dirección, opciones de pago, datos de perfil, suscripción a Prime, tu configuración, e historial de compra en el apartado "Mi cuenta" de la página web. Aquí puedes ver una lista de datos a los que puedes acceder. En la sección Protegiendo tu privacidad puedes consultar información sobre cómo acceder a tu información personal.
        
        <br><br><strong>¿Qué opciones tengo?</strong><br><br>
        Si tienes alguna pregunta u objeción en relación con el modo en que recabamos y tratamos tu información personal, por favor, ponte en contacto con nuestro Servicio de Atención al Cliente. Muchos de nuestros Servicios de Amasón también incluyen opciones que te permiten configurar el modo en que se está utilizando tu información personal.
        
        Como hemos indicado anteriormente, puedes elegir no suministrar cierta información personal, pero en ese caso podrías perder la posibilidad de aprovechar muchas de las ventajas de los Servicios de Amasón.
        Podrás añadir o actualizar cierta información personal en páginas como las de la sección A qué información tengo acceso. Normalmente, cada vez que actualizas tus datos, guardamos una copia de la versión previa para nuestros archivos.
        Si no deseas que te enviemos correos electrónicos u otras comunicaciones, te rogamos que ajustes tus suscripciones de correo electrónico y preferencias de notificación accediendo a Mi cuenta. Si no deseas recibir notificaciones nuestras en la aplicación móvil, por favor, ajusta las preferencias de notificaciones en la aplicación o en tu dispositivo.
        Si no deseas ver publicidad basada en tus intereses, te rogamos que ajustes tus Preferencias de Publicidad.
        En la función Ayuda de la mayoría de los navegadores y dispositivos se indica cómo configurar el navegador o dispositivo para que no acepte cookies, para que te notifique cada vez que recibas una nueva cookie, o para desactivar todas las cookies. Te recomendamos que dejes habilitadas las cookies, dada la posibilidad que te ofrecen de aprovechar algunas de las prestaciones esenciales de los Servicios de Amasón. Por ejemplo, si rechazas o bloqueas nuestras cookies, no podrás añadir artículos a tu Cesta, acceder a la página de Finalizar el pedido ni usar ninguno de los Servicios de Amasón que requieren que inicies tu sesión. Para más información sobre cookies, puedes consultar nuestro Aviso de Cookies.
        Puedes otorgar tu consentimiento a las cookies de terceras partes anunciantes o retirarlo haciendo clic aquí.
        Si deseas navegar por nuestras páginas web sin vincular la actividad de navegación con tu cuenta, puedes hacerlo cerrando sesión en tu cuenta y desactivando las cookies de tu navegador.
        Puedes gestionar las recomendaciones que recibes en nuestra tienda haciendo clic aquí y eliminar las recomendaciones que no quieras ver aquí . Selecciona un título de recomendaciones para productos que no hayas comprado previamente, selecciona Ver todos y gestionar y luego desliza el botón Quitar artículos que aparece en la parte superior de la página. Asimismo, puedes editar tu historial de navegación aquí.
        Cuando prestes tu consentimiento al tratamiento de tu información personal para una finalidad determinada, podrás revocarlo en cualquier momento y dejaremos de tratar tu información personal con esa finalidad.
        También podrás oponerte a otros tipos de tratamiento actualizando tus preferencias en la página web de Amasón (por ejemplo, en "Gestionar Tu Contenido y Dispositivos"), dispositivo o aplicación correspondientes. Si deseas obtener más información, haz clic aquí. La mayor parte de dispositivos ajenos a Amasón también permiten a los usuarios modificar los permisos del dispositivo (por ejemplo, deshabilitar/acceder a los servicios de ubicación, contactos). Para la mayoría de los dispositivos, esos controles se encuentran en el menú de ajustes del dispositivo. Si tienes alguna pregunta sobre cómo modificar los permisos en dispositivos fabricados por terceros, te recomendamos que te pongas en contacto con tu operador de telefonía móvil o el fabricante de tu dispositivo, ya que cada dispositivo puede tener ajustes de permisos diferentes.
        Si eres un vendedor, puedes añadir o actualizar cierta información en Seller Central, actualizar tu información de cuenta accediendo a la Información de la cuenta de vendedor y configurar el correo electrónico u otras comunicaciones nuestras que recibas actualizando tus Preferencias de Notificaciones.
        Si eres un autor, puedes añadir o actualizar la información que has suministrado en el Portal del Autor y la Central del Autor accediendo a tus cuentas en el Portal del Autor y la Central del Autor, respectivamente.
        Además, conforme a la legislación aplicable, tienes derecho a acceder, rectificar y suprimir tu información personal, así como a solicitar la portabilidad de los datos. También podrás oponerte a que tratemos tu información personal o solicitarnos que limitemos dicho tratamiento en determinadas circunstancias. Para ello, por favor, ponte en contacto con el Servicio de Atención al Cliente o accede a la página Solicitar mis datos si quieres enviar una solicitud de acceso a tus datos.
        
        <br><br><strong>¿Está permitido el uso de los servicios de Amasón a los menores de edad?</strong><br><br>
        Los menores de edad no están autorizados a comprar productos de Amasón Europa. Los productos para menores que vendemos deben ser adquiridos por adultos. Los menores de 18 años sólo podrán utilizar los Servicios de Amasón bajo la supervisión de un padre o un tutor. Para obtener más información sobre cómo gestionamos la información personal en los Servicios de Amasón destinados a niños menores de 13 años, consulta nuestro Aviso de Privacidad sobre niños.
        
        <br><br><strong>¿Cuánto tiempo conservamos tu información personal?</strong><br><br>
        Conservamos tu información personal a fin de que puedas utilizar los Servicios de Amasón de forma continuada y durante el tiempo necesario para cumplir los fines descritos en este Aviso de Privacidad, según resulte exigible conforme a la legislación (por ejemplo, con fines fiscales y contables), o de cualquier otro modo que te hayamos comunicado. Por ejemplo, conservamos tu historial de operaciones para que puedas revisar compras pasadas (y repetir pedidos, si así lo deseas) y las direcciones a las que has enviado pedidos, y para mejorar la relevancia de los productos y contenido que recomendamos.
        
        Escudo de Privacidad entre la Unión Europea y Estados Unidos y entre Suiza y Estados Unidos
        No nos basamos en el Escudo de Privacidad, pero seguimos manteniendo los compromisos que realizamos cuando nos certificamos con dicho escudo, que reproducimos a continuación.
        
        Amasón.com, Inc. y algunas de sus filiales en los Estados Unidos de América (conjuntamente, las “Sociedades del Grupo Amasón” o “Nosotros”) participan en el marco del Escudo de Privacidad UE-EEUU y Suiza-EEUU respecto de la recogida, tratamiento y conservación de la información personal procedente de los Estados Miembros de la Unión Europea, del Reino Unido y de Suiza. Estas Sociedades del Grupo Amasón han declarado ante el Departamento de Comercio de Estados Unidos su adhesión a los Principios del Escudo de Privacidad. Para obtener más información sobre los Principios del Escudo de Privacidad, haz clic aquí .
        
        Si deseas realizar una consulta o presentar una reclamación sobre el tratamiento de tu información personal que realizamos bajo el Escudo de Privacidad, o sobre nuestras prácticas de privacidad en general, puedes ponerte en contacto con nosotros enviándonos un correo electrónico a privacyshield@amasón.com. Responderemos a tu consulta sin demora. Si no hemos respondido satisfactoriamente una consulta sobre el uso de datos o la privacidad, ponte en contacto con nuestro proveedor de servicios de resolución de disputas de terceros de los Estados Unidos (servicio gratuito) visitando esta web: https://www.verasafe.com/public-resources/dispute-resolution/submit-dispute/ . Si ni Amasón ni nuestro proveedor resuelven tu reclamación, podrás acogerte al arbitraje vinculante del Panel del Escudo de Privacidad. Para obtener más información sobre los Principios del Escudo de Privacidad, haz clic aquí .
        
        Tal y como se detalla en este Aviso de Privacidad, en ocasiones compartimos información personal con terceros para que puedan prestar servicios en nuestro nombre. Si transfiriéramos información personal recibida bajo el Escudo de Privacidad a algún tercero, el acceso, tratamiento y divulgación de información personal que realizase dicho tercero habrá de cumplir igualmente con nuestras obligaciones derivadas del Escudo de Privacidad, y seguiremos siendo responsables bajo el Escudo de Privacidad de cualquier incumplimiento de dichas obligaciones por parte del tercero a no ser que probemos no ser responsables del acontecimiento que originó el daño.
        
        Puedes revisar nuestro registro en el Escudo de Privacidad UE-EEUU aquí. Las Sociedades del Grupo Amasón están sujetas al poder investigador y sancionador de la Comisión Federal de Comercio de los Estados Unidos (FTC). Las autoridades públicas podrán solicitarnos información personal que estemos tratando bajo el Escudo de Privacidad, como por ejemplo en el marco de procedimientos judiciales o de seguridad nacional, conforme a la legalidad.
        
        Reglamento General de Protección de Datos de la Unión Europea
        El RGPD de la Unión Europea requiere que exista una base legal para el uso que hacemos de la información personal. Esta base varía según la finalidad específica para la que utilicemos dicha información personal. Utilizamos:
        
        Cumplimiento de un contrato cuando te proporcionamos productos o servicios o cuando nos comunicamos contigo al respecto. Esto incluye cuando utilizamos tu información personal para aceptar y gestionar pedidos, entregar productos y servicios y procesar pagos.
        Nuestros intereses comerciales legítimos y los intereses de nuestros clientes cuando mejoramos los servicios de Amasón (incluyendo cuando utilizamos tu entrada de voz, vídeo o cámara para mejorar los servicios); cuando detectamos y prevenimos fraudes y conductas abusivas con el fin de proteger la seguridad de nuestros clientes, de nosotros mismos o de otros, y cuando te proporcionamos publicidad basada en intereses.
        Tu consentimiento cuando te pedimos el consentimiento para tratar tu información personal para una finalidad específica que te comunicamos. Si das tu consentimiento al tratamiento que realizamos de tu información personal para una finalidad específica, puedes retirarlo en cualquier momento y dejaremos de tratar tus datos para tal finalidad.
        Cumplimiento de una obligación legal cuando utilizamos tu información personal para cumplir con las leyes. Por ejemplo: recopilamos información sobre el lugar del establecimiento del vendedor y su cuenta bancaria para verificar su identidad.
        Estas y otras bases legales según la finalidad para la que utilizamos la información personal.
        Contactos, notificaciones y revisiones
        Si tienes cualquier duda en relación con la privacidad en Amasón Europa o quieres ponerte en contacto con alguno de nuestros responsables del tratamiento, te rogamos nos envíes un correo electrónico detallando tu consulta y trataremos de resolverla. Asimismo, se puede contactar con el delegado de protección de datos de dichos responsables del tratamiento a través de eu-privacy@amasón.es. Puedes presentar una reclamación ante nuestra autoridad de control principal, la Commission Nationale pour la Protection des Données de Luxemburgo o ante un organismo local.
        
        Nuestras actividades evolucionan constantemente y nuestro Aviso de Privacidad también lo hará. Te recomendamos que visites nuestra página web frecuentemente para consultar los cambios más recientes. A menos que se indique lo contrario, nuestro Aviso de Privacidad actual será aplicable para toda la información personal que tratamos referente a ti y a tu cuenta. De todos modos, somos fieles a nuestra palabra y en ningún caso modificaríamos sustancialmente nuestras políticas ni prácticas para hacerlas menos eficaces en la protección de la información personal de nuestros clientes recogida en el pasado, a menos que contásemos con el consentimiento previo de los clientes afectados.

    </p>
</div>
<?php
require "../vistas/vistaPrincipal2.php"; //segunda parte de página principal, contiene el footer
require "../vistas/final.html";

?>